### ISSUE TITLE
[terraform-ibm-event-streams] Change the name of the DA flavor / variation

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-event-streams#246]
We don't want to use the name `fscloud` as the flavor / variation for the DA. Actions:

- Rename dir: `solutions/fscloud` -> `solutions/standard`
- `ibm_catalog.json` updates:
  - Update `working_directory` to new dir (`solutions/standard`)
  - Update flavor name and label to `standard` / `Standard`
- Update variation name in `.catalog-onboard-pipeline.yaml`

**Comment by Soaib024** [comment]
PR merged - hence closing the issue
