### ISSUE TITLE
Use parameters_json instead of parameters in the ibm_resource_instance

### ISSUE THREAD

**Issue by kccox** [terraform-ibm-modules/terraform-ibm-event-streams#322]
### Description

The `ibm_resource_instance` declarations in the Event Streams modules use a `parameters` block ([example](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/blob/731401e4d567b72a0f12657aa662427c31e1f871/main.tf#L50-L55)).  Event Streams is adding provisioning features such as mirroring that use complex structured inputs and cannot be specified with `parameters`. To make these features available in the module, the resource instance should use the `parameters_json` declaration.

The change will be largely transparent to users, as it will use the same variables as the current approach, changing the module `main.tf` to insert these into a `parameters_json` block instead of the `parameters` block.

The Event Streams development team plans to make this change, as the new provisioning features are requested by one of our customers. We are opening this issue to invite comments.

### New or affected modules

terraform-ibm-event-streams

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by JunliWang** [comment]
the example of `parameters_json` can be found here
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-event-streams/main.tf#L122-L129
it could be more complex like below:
```tf 
parameters_json = jsonencode(
    {
      mirroring = {
        source_crn   = data.ibm_resource_instance.es_instance_source.id
        source_alias = "source-alias"
        target_alias = "target-alias"
        options = {
          topic_name_transform = {
             type = "rename" 
             rename = {
               add_prefix = "add_prefix"
               add_suffix = "add_suffix"
               remove_prefix = "remove_prefix"
               remove_suffix = "remove_suffix"
             }
          }
          group_id_transform = {
            type = "rename" 
            rename = {
               add_prefix = "add_prefix"
               add_suffix = "add_suffix"
               remove_prefix = "remove_prefix"
               remove_suffix = "remove_suffix"
            }
          }
        }
      }
    }
  )
  ```

**Comment by ocofaigh** [comment]
@JunliWang why take the approach of `parameters_json` here instead of creating separate provider resources. It means the config parameters can only be set when provisioning a new instance. What if someone wanted to update an exiting instance?

**Comment by JunliWang** [comment]
provision ES instance with mirroring support can only be done via `parameter_json` given its complex json structure.
and after mirroring is added, we do not support updating source_alias/target_alias or any other mirroring options.
use can update instance with below json to disable mirroring
```tf
parameters_json = jsonencode(
    {
      mirroring = {
         disable = true
      }
   }
)
```

**Comment by ocofaigh** [comment]
@JunliWang Are you saying these configurations can only be done on initial provisioning of the instance? If so thats fair enough. However if these configs can be set on an existing instance, I would suggest they should have their own terraform provider resources.

**Comment by JunliWang** [comment]
instance can be provisioned without mirroring, then later update to add mirroring capability, by adding that complex mirroring structure via parameters_json.

**Comment by ocofaigh** [comment]
PR under review: https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/325

**Comment by JunliWang** [comment]
close as done
