### ISSUE TITLE
[Event Streams] Scope KMS policy to the exact KMS key

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-event-streams#329]
The policy [here](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/blob/88d2e35f60b860de45786610e267526a57b4aac4/main.tf#L103-L112) can be updated to scope it to the exact KMS key. For an example of the syntax, see https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/764

**Comment by akocbek** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/351
