### ISSUE TITLE
Don't expose so many variables in the Event Streams module examples

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-event-streams#331]
We should not be exposing `schemas`, or `topics` as input variables in any of the examples. Instead we should add some value for them directly in the main.tf of the example itself to avoid users trying to consume them as consumable solutions.
Examples are not intended for that.

**Comment by aatreyee2506** [comment]
Closing this as the [PR](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/354) got merged.
