### ISSUE TITLE
Support creating and deleting topics irrespective of topic index

### ISSUE THREAD

**Issue by navidsh** [terraform-ibm-modules/terraform-ibm-event-streams#349]
### Description

Currently, when adding or removing topics from the beginning or middle of the list of topics, Terraform suggests renaming many topics. For example, adding a new topic (`topics_0`) to an existing list of topic `[topics_1, topics_2, topics_3] -> [topics_0, topics_1, topics_2, topics_3]` would trigger Terraform to rename all existing topics:

```sh
> terraform plan 
...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic[0] will be updated in-place
  ~ resource "ibm_event_streams_topic" "es_topic" {
        id                   = "crn:v1:bluemix:public:messagehub:us-south:a/account-id:es-id:topic:topic_1"
      ~ name                 = "topic_1" -> "topic_0"
        # (5 unchanged attributes hidden)
    }
...
  # module.event_streams.ibm_event_streams_topic.es_topic[3] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_3"
      + partitions           = 6
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/account-id:es-id::"
    }

Plan: 1 to add, 3 to change, 0 to destroy.
```

I found a similar issue with a possible workaround in https://github.com/hashicorp/terraform/issues/14275. Also https://github.com/hashicorp/terraform/issues/17179 addresses the exact same issue.

### New or affected modules

[terraform-ibm-event-streams](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
PR under review: https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/350

**Comment by ocofaigh** [comment]
Fixed in https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/releases/tag/v3.0.0
