### ISSUE TITLE
FSCloud profile for EventStreams

### ISSUE THREAD

**Issue by jor2** [terraform-ibm-modules/terraform-ibm-event-streams#5]
- Create FSCloud profile submodule
- Create FSCloud example that calls the submodule
- Ensure CRA is pointing to new FSCloud example
- Ensure SCC scan is passing on the EventStreams instance created by the FSCloud profile

**Comment by Ak-sky** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/releases/tag/v1.3.0
